config/routes.rb
SpecialMap::Application.routes.draw do
  resources :specials
  root :to => "home#location"

  match "/nearby" => "home#nearby", as: "nearby"
  match "/mobile" => "home#mobile", as: "mobile"

  resources :restaurants

end

app/models/restaurant.rb
require 'open-uri'

class Restaurant < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :name
  has_many :specials
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def self.download
    neighborhoods = [ "Albany%20Park", 
                      "Andersonville", 
                      "Avondale", 
                      "Bridgeport", 
                      "Bucktown", 
                      "Edgewater", 
                      "Edison%20Park", 
                      "Humboldt%20Park", 
                      "Irving%20Park", 
                      "Jefferson%20Park", 
                      "Lakeview", 
                      "Lincoln%20Park", 
                      "Lincoln%20Square", 
                      "Logan%20Square", 
                      "Loop", 
                      "Near%20North%20Side", 
                      "Near%20West%20Side", 
                      "Noble%20Square", 
                      "North%20Center", 
                      "Old%20Town", 
                      "Pilsen", 
                      "Printers%20Row", 
                      "River%20North", 
                      "Rogers%20Park", 
                      "Roscoe%20Village", 
                      "South%20Loop", 
                      "Streeterville", 
                      "Ukrainian%20Village", 
                      "University%20Village", 
                      "Uptown", 
                      "West%20Loop", 
                      "West%20Rogers%20Park", 
                      "Wicker%20Park", 
                      "Wrigleyville" ]

    days = { "Monday"    => 1,
             "Tuesday"   => 2, 
             "Wednesday" => 3, 
             "Thursday"  => 4, 
             "Friday"    => 5, 
             "Saturday"  => 6, 
             "Sunday"    => 7 }

    neighborhoods.each do |neighborhood|    

      days.keys.each do |day|
        doc = Nokogiri::HTML(open("http://www.smalltabs.com/sort.php?day=#{day}&neighborhood=#{neighborhood}"))

        doc.css('a.special').each do |block|
          @blockname = ""
          @blockaddr = ""
          @blockfood = ""
          @blockdrink = ""
          @blockevent = ""
          block.css('h3').each { |item| @blockname = item.content }
          block.css('p.meta').each do |item| 
            @blockaddr = item.content.split('@').reverse.join(', ').strip
            @blockaddr << ", Chicago, IL"
          end
          block.css('li.food').each { |item|   @blockfood  = item.content }
          block.css('li.drink').each { |item|  @blockdrink = item.content }
          block.css('li.events').each { |item| @blockevent = item.content }


          restaurant = Restaurant.find_by_name(@blockname) || Restaurant.create(name: @blockname, address: @blockaddr)
          if special = Special.find_by_restaurant_id_and_day(restaurant.id, days[day])
            special[food:  @blockfood, 
                   drink: @blockdrink, 
                   event: @blockevent]
          else
            Special.create(food:  @blockfood, 
                 drink: @blockdrink, 
                 event: @blockevent, 
                 restaurant_id: restaurant.id,
                 day: days[day])
          end
          sleep(0.2)
        end
      end
      sleep(0.25)
    end
  end
end

app/models/special.rb
class Special < ActiveRecord::Base
  attr_accessible :day, :drink, :event, :food, :restaurant_id
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def nearby
		@location = { latitude: params[:latitude], longitude: params[:longitude] }
	end

	def mobile
		@location = { latitude: params[:latitude], longitude: params[:longitude] }
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  # GET /specials
  # GET /specials.json
  def index
    @specials = Special.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specials }
    end
  end

  # GET /specials/1
  # GET /specials/1.json
  def show
    @special = Special.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @special }
    end
  end

  # GET /specials/new
  # GET /specials/new.json
  def new
    @special = Special.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @special }
    end
  end

  # GET /specials/1/edit
  def edit
    @special = Special.find(params[:id])
  end

  # POST /specials
  # POST /specials.json
  def create
    @special = Special.new(params[:special])

    respond_to do |format|
      if @special.save
        format.html { redirect_to @special, notice: 'Special was successfully created.' }
        format.json { render json: @special, status: :created, location: @special }
      else
        format.html { render action: "new" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specials/1
  # PUT /specials/1.json
  def update
    @special = Special.find(params[:id])

    respond_to do |format|
      if @special.update_attributes(params[:special])
        format.html { redirect_to @special, notice: 'Special was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specials/1
  # DELETE /specials/1.json
  def destroy
    @special = Special.find(params[:id])
    @special.destroy

    respond_to do |format|
      format.html { redirect_to specials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def has_specials?(place, day)
		if @special = place.specials.find{ |x| x[:day] == day }
			if !@special.food.empty? || !@special.drink.empty? || !@special.event.empty?
				true
			end
		end
	end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/home/location.html.erb
<script>
  function doGeolocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(positionSuccess, positionError );
    } else {
      positionError(-1);
    }
  }

  function positionError(err) {
    var msg;
    switch(err.code) {
      case err.UNKNOWN_ERROR:
        msg = "Unable to find your location";
        break;
      case err.PERMISSION_DENINED:
        msg = "Permission denied in finding your location";
        break;
      case err.POSITION_UNAVAILABLE:
        msg = "Your location is currently unknown";
        break;
      case err.BREAK:
        msg = "Attempt to find location took too long";
        break;
      default:
        msg = "Location detection not supported in browser";
    }
    document.getElementById('info').innerHTML = msg;
  }

  function positionSuccess(position) {
    // Centre the map on the new location
    var coords = position.coords || position.coordinate || position;
    if ( $(window).width() < 600 ) {
      window.location.href =  'mobile' + '?latitude=' + coords.latitude + '&longitude=' + coords.longitude
    } else {
      window.location.href =  'nearby' + '?latitude=' + coords.latitude + '&longitude=' + coords.longitude
    }
  }
</script>

app/views/home/mobile.html.erb
<% cur_location = [@location[:latitude], @location[:longitude]] %>
<% nearbys = Restaurant.near( cur_location, 0.4) %>
<% nearbys = Restaurant.near( cur_location, 0.3) if nearbys.length > 25 %>
<% nearbys = Restaurant.near( cur_location, 0.5) if nearbys.length < 10 %>
<% nearbys = Restaurant.near( cur_location, 0.7) if nearbys.length < 10 %>

<div class="links">
	<%= link_to "Refresh Location", root_path %> -- 
	<a href="#" onclick="$('.m-food, .m-drink, .m-event').toggle()">Collapse all</a>
</div>

<div class="links">
	Showing <%= Time.now.strftime("%A") %> specials
</div>

<% nearbys.each do |place| %>
	<% next if !has_specials?(place, Time.now.wday) %>
	<div class="m-place">
		<%= content_tag :h4, place.name %>
		<%= content_tag :h6, link_to(place.address[0,place.address.index(',')], "http://maps.apple.com/?q=#{place.address[0,place.address.index(',')]}, Chicago IL")  %>
		<span class="m-direction">
			<i class="icon-arrow-down" style="display:inline-block;-webkit-transform:rotate(<%= place.bearing_to(cur_location).to_f %>deg);"></i>
			<%= place.distance_to(cur_location).to_f.round(2) %> mi
		</span>
		<%= content_tag( :span, @special.food,  class: "m-food" )  if !@special.food.empty? %>
		<%= content_tag( :span, @special.drink, class: "m-drink" ) if !@special.drink.empty? %>
		<%= content_tag( :span, @special.event, class: "m-event" ) if !@special.event.empty? %>
	</div>
<% end %>

app/views/home/nearby.html.erb
<% cur_location = [@location[:latitude], @location[:longitude]] %>
<% nearbys = Restaurant.near( cur_location, 0.4) %>
<% nearbys = Restaurant.near( cur_location, 0.3) if nearbys.length > 25 %>
<% nearbys = Restaurant.near( cur_location, 0.5) if nearbys.length < 10 %>
<% nearbys = Restaurant.near( cur_location, 0.7) if nearbys.length < 10 %>


<div id="refresh"><%= link_to "Refresh Location", root_path %></div>
<table class="table-striped table-bordered">
	<tr>
		<th>Restaurant</th>
		<th>Direction</th>
		<th>Food</th>
		<th>Drink</th>
	</tr>
	<% nearbys.each do |place| %>
	<tr>
		<td>
			<strong><%= place.name %></strong><br>
			<%= place.address[0,place.address.index(',')] %>
			</td>
		<td>
			<i class="icon-arrow-down" style="display:inline-block;-webkit-transform:rotate(<%= place.bearing_to(cur_location).to_f %>deg);"></i>
			<a href="#map" onclick="$('img').attr('src', $('img').attr('src').replace(/green%7C<%= place.latitude %>/g, 'red%7C<%= place.latitude %>'));">
				<%= place.distance_to(cur_location).to_f.round(2) %> mi
			</a>
		</td>
		<% special = place.specials.find{ |x| x[:day] == Time.now.wday } %>
		<td class="food"><%= special.food if special %></td>
		<td class="drink"><%= special.drink if special %></td>

	</tr>
<% end %>
<table>
<% markers = "" %>
<% nearbys.each { |place| markers << "&markers=color:green%7C#{place[:latitude]},#{place[:longitude]}"} %>

<div id="map">
	<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@location[:latitude]},#{@location[:longitude]}&zoom=16&size=640x500&maptype=roadmap&markers=color:blue%7C#{@location[:latitude]},#{@location[:longitude]}#{markers}&sensor=false" %>
</div>

app/views/layouts/_locate.html.erb
<script type="text/javascript">
  var map;
  function initialise() {
    var latlng = new google.maps.LatLng(-25.363882,131.044922);
    var myOptions = {
      zoom: 4,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.TERRAIN,
      disableDefaultUI: true
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    prepareGeolocation();
    doGeolocation();
  }

  function doGeolocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(positionSuccess, positionError);
    } else {
      positionError(-1);
    }
  }

  function positionError(err) {
    var msg;
    switch(err.code) {
      case err.UNKNOWN_ERROR:
        msg = "Unable to find your location";
        break;
      case err.PERMISSION_DENINED:
        msg = "Permission denied in finding your location";
        break;
      case err.POSITION_UNAVAILABLE:
        msg = "Your location is currently unknown";
        break;
      case err.BREAK:
        msg = "Attempt to find location took too long";
        break;
      default:
        msg = "Location detection not supported in browser";
    }
    document.getElementById('info').innerHTML = msg;
  }

  function positionSuccess(position) {
    // Centre the map on the new location
    var coords = position.coords || position.coordinate || position;
    var latLng = new google.maps.LatLng(coords.latitude, coords.longitude);
    map.setCenter(latLng);
    map.setZoom(12);
    var marker = new google.maps.Marker({
      map: map,
      position: latLng,
      title: 'Why, there you are!'
    });
    document.getElementById('info').innerHTML = 'Looking for <b>' +
        coords.latitude + ', ' + coords.longitude + '</b>...';

    // And reverse geocode.
    (new google.maps.Geocoder()).geocode({latLng: latLng}, function(resp) {
      var place = "You're around here somewhere!";
      if (resp[0]) {
        var bits = [];
        for (var i = 0, I = resp[0].address_components.length; i < I; ++i) {
          var component = resp[0].address_components[i];
          if (contains(component.types, 'political')) {
            bits.push('<b>' + component.long_name + '</b>');
          }
        }
        if (bits.length) {
          place = bits.join(' > ');
        }
        marker.setTitle(resp[0].formatted_address);
      }
      document.getElementById('info').innerHTML = place;
    });
  }

  function contains(array, item) {
    for (var i = 0, I = array.length; i < I; ++i) {
      if (array[i] == item) return true;
    }
    return false;
  }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpecialMap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "geometa" %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
</head>
<body onload="doGeolocation()">

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurants.each do |restaurant| %>
  <tr>
    <td><%= restaurant.name %></td>
    <td><%= restaurant.address %></td>
    <td><%= restaurant.latitude %></td>
    <td><%= restaurant.longitude %></td>
    <td><%= link_to 'Show', restaurant %></td>
    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @restaurant.name %>
</p>

<p>
  <b>Address:</b>
  <%= @restaurant.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @restaurant.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @restaurant.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=15&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>
<br>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/specials/_form.html.erb
<%= form_for(@special) do |f| %>
  <% if @special.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special.errors.count, "error") %> prohibited this special from being saved:</h2>

      <ul>
      <% @special.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :food %><br />
    <%= f.text_field :food %>
  </div>
  <div class="field">
    <%= f.label :drink %><br />
    <%= f.text_field :drink %>
  </div>
  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specials/edit.html.erb
<h1>Editing special</h1>

<%= render 'form' %>

<%= link_to 'Show', @special %> |
<%= link_to 'Back', specials_path %>

app/views/specials/index.html.erb
<h1>Listing specials</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Food</th>
    <th>Drink</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specials.each do |special| %>
  <tr>
    <td><%= special.day %></td>
    <td><%= special.food %></td>
    <td><%= special.drink %></td>
    <td><%= special.event %></td>
    <td><%= link_to 'Show', special %></td>
    <td><%= link_to 'Edit', edit_special_path(special) %></td>
    <td><%= link_to 'Destroy', special, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Special', new_special_path %>

app/views/specials/new.html.erb
<h1>New special</h1>

<%= render 'form' %>

<%= link_to 'Back', specials_path %>

app/views/specials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @special.day %>
</p>

<p>
  <b>Food:</b>
  <%= @special.food %>
</p>

<p>
  <b>Drink:</b>
  <%= @special.drink %>
</p>

<p>
  <b>Event:</b>
  <%= @special.event %>
</p>


<%= link_to 'Edit', edit_special_path(@special) %> |
<%= link_to 'Back', specials_path %>